os: Windows Server 2012 R2
environment:
  matrix:
  - GENERATOR: MinGW Makefiles
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#     platform: x64

configuration: Debug

# clone_script:
#   - git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
#   - cd %APPVEYOR_BUILD_FOLDER%
#   - git checkout -qf %APPVEYOR_REPO_COMMIT%
#   - git submodule update --init --recursive

install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive

before_build:
  - dir C:\mingw-w64\
  - dir C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\
  - dir C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64
  - rm -rf build
  - rm -rf stage
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - set PATH=C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin;%PATH%
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=%CONFIGURATION% -G "%GENERATOR%" -DCMAKE_INSTALL_PREFIX="../stage" -DBUILD_TEST="ON"

build_script: cmake --build . --config %CONFIGURATION% --target install

test_script: 
  - ctest